config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  get 'landing/index'
  root 'landing#index'

  resources :requests
  resources :profiles
  resources :changelogs
  resources :contractors
  resources :registrations
  resources :signuptokens

  resources :requests do
    resources :changelogs
    patch :approve
    put :approve
    patch :cancel
    put :cancel
  end

  resources :requests do
    get 'note', on: :new
  end

  namespace :api do
    namespace :v1 do
      resources :requests, only: [:index, :update, :show, :create, :destroy]
    end
  end
  namespace :api do
    namespace :v1 do
      resources :approvals, only: [:index, :update, :show, :create]
    end
  end
  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index, :update, :show, :create]
    end
  end
  namespace :api do
    namespace :v1 do
      resources :newsfeeds, only: [:index, :update, :show, :create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :signuptokens, only: [:index, :update, :show, :create, :destroy]
    end
  end


  root to: 'landing#index'

end

app/controllers/api/v1/profiles_controller.rb
class Api::V1::ProfilesController < ApplicationController

  def update
  end

  def show
    target_user = User.where(id: params[:id])[0]
    if target_user.active == true
      target_user.active = false
      target_user.save

    else
      target_user.active = true
      target_user.save
    end
    response = true
    render json: response

  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, except: [:new, :edit]
  def index
    @user = current_user
    @users = User.all
  end

  def show
    @user = User.where(id: params[:id])[0]
    @logged_in_user = current_user

  end

  def update
    @logged_in_user = current_user
    @user = User.where(id: params[:id])[0]
    if params[:updates][:new_role] != 'no_change'
      @user.role = params[:updates][:new_role]
    end
    if params[:updates][:new_approval_group] != 'no_change'
      @user.approval_group = params[:updates][:new_approval_group]
    end
    @user.save!
    render :show
  end

  def edit
  end

  def new
  end

end

app/views/profiles/index.html.erb
<% if @user.role == "admin" || @user.role == "superadmin" %>
<div id="token_space">
  -
</div>
<button type="button" name="generate_signuptoken" id="generate_token">Generate Signup Token</button>
<% end %>
<% if @user.role == "superadmin" %>
<br>
<br>
<div id="superadmin_token_space">
  Currently Active Tokens:
  <ul>
  <% Signuptoken.all.each do |t| %>
    <li><%= t.token_text %></li>
  <% end %>
  </ul>
</div>
<br>
<a href="<%= signuptokens_path %>" class="fakebutton" id="clear_signuptokens">Clear All Signup tokens</a>
<% end %>

<ul>
  <% @users.each do |user| %>
    <li class="user_line"><a href="<%= profile_path(user) %>" class="fakebutton user_edit">Edit</a><%= user.name %>, <%= user.email %>, <%= user.phone %></li>
  <% end %>
</ul>

app/views/profiles/new.html.erb

<%= form_tag(edit_requests_path, method: "get") do %>
  <%= label_tag(:year, "Year:") %>
  <%= number_field_tag(:year, @thisyear) %>

  <%= submit_tag("Filter") %>
<% end %>

app/views/profiles/show.html.erb
<ul>
  <li>Name: <%= @user.name %></li>
  <li>Email: <%= @user.email %></li>
  <li>Phone #: <%= @user.phone %></li>
  <li>Company: <%= @user.company %></li>
  <li>Role: <%= @user.role %></li>
  <li>Approval Group: <%= @user.approval_group %></li>
  <li>Status: <% if @user.active == true %>Active<% else %>Deactivated<% end %></li>

</ul>

<form action="/profiles/<%= @user.id %>" method="post">
  <input name="_method" type="hidden" value="patch" />
  <select name="updates[new_role]">
    <% if @logged_in_user.role == "superadmin" %>
      <%= options_for_select([['Select New Role', 'no_change'], ['Admin', 'admin'], ['User', 'user'], ['Investigator', 'investigator'], ['Superadmin', 'superadmin']]) %>
    <% else %>
      <%= options_for_select([['Select New Role', 'no_change'], ['Admin', 'admin'], ['User', 'user'], ['Investigator', 'investigator']]) %>
    <% end %>
  </select>
  <br>
  <select name="updates[new_approval_group]">
    <%= options_for_select([['Select New Approval Group', 'no_change'], ['No Approval Rights', 0], ['Group 1', 1], ['Group 2', 2], ['Group 3', 3], ['Group 4', 4]]) %>
  </select>
  <br>
  <input name="commit" type="submit" value="Update User" />
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
</form>

<button type="button" class="fakebutton" id="deactivate_user" data-userid="<%= @user.id %>"><% if @user.active == true %>Deactivate User<% else %>Re-activate User<% end %></button>