config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  get 'landing/index'
  root 'landing#index'

  resources :requests
  resources :profiles
  resources :changelogs
  resources :contractors
  resources :registrations
  resources :signuptokens

  resources :requests do
    resources :changelogs
    patch :approve
    put :approve
    patch :cancel
    put :cancel
  end

  resources :requests do
    get 'note', on: :new
  end

  namespace :api do
    namespace :v1 do
      resources :requests, only: [:index, :update, :show, :create, :destroy]
    end
  end
  namespace :api do
    namespace :v1 do
      resources :approvals, only: [:index, :update, :show, :create]
    end
  end
  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index, :update, :show, :create]
    end
  end
  namespace :api do
    namespace :v1 do
      resources :newsfeeds, only: [:index, :update, :show, :create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :signuptokens, only: [:index, :update, :show, :create, :destroy]
    end
  end


  root to: 'landing#index'

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  # this makes sense, but unless you're going to redirect_to a login screen, i thknk this'll
  # just break? If that's what you want, raise an error here to make their shit explode
  # and stop execution.
  
  def index
    if user_signed_in?
      @user = current_user
      redirect_to requests_url
    else
      @user = nil
    end
  end
end

app/views/landing/index.html.erb
<div id="dash_main">
  <div class="page_title">
    <%= image_tag "Caltrain_logo_4color clear background.png", alt: "Logo", id: "caltrain_logo" %>

    <h1>Right to Work Request Portal</h1>
  </div>
  <% if @user != nil %>
    <% if @user.role == 'admin' || @user.role == 'superadmin' %>
      <div class="control_panel">
        <a href="<%= profiles_path %>">Users</a>
        <br>
        <a href='<%= requests_path %>'>Requests</a>
      </div>
    <% elsif @user.role == 'inspector' %>
    <% end %>
      <div class="account_summary">
        <ul>

        <% @user.requests.each do |request| %>
          <li><%= request.title%>: submitted on <%= request.created_at%></li>
        <% end %>
      </ul>
      </div>
      <br>
      <div class="control_panel">
        <a href="<%= new_request_path %>">New Request Form</a>
        <br>
        <a href='<%= requests_path %>'>Requests</a>
      </div>
  <% end %>
</div>