config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  get 'landing/index'
  root 'landing#index'

  resources :requests
  resources :profiles
  resources :changelogs
  resources :contractors
  resources :registrations
  resources :signuptokens

  resources :requests do
    resources :changelogs
    patch :approve
    put :approve
    patch :cancel
    put :cancel
  end

  resources :requests do
    get 'note', on: :new
  end

  namespace :api do
    namespace :v1 do
      resources :requests, only: [:index, :update, :show, :create, :destroy]
    end
  end
  namespace :api do
    namespace :v1 do
      resources :approvals, only: [:index, :update, :show, :create]
    end
  end
  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index, :update, :show, :create]
    end
  end
  namespace :api do
    namespace :v1 do
      resources :newsfeeds, only: [:index, :update, :show, :create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :signuptokens, only: [:index, :update, :show, :create, :destroy]
    end
  end


  root to: 'landing#index'

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_many :changelogs
  has_many :notes
  has_many_attached :attachments
  has_one :weekly
  has_one :pending
  has_one :approval

  validates :year, presence: {message: 'Year must not be blank'}
  validates :week, presence: {message: 'Week must not be blank'}
  validates :contractor, presence: {message: 'Company name must not be blank'}
  validates :description, presence: {message: 'Description must not be blank'}
  validates :requestor_name, presence: {message: 'Name must not be blank'}
  validates :requestor_email, presence: {message: 'Email must not be blank'}
  validates :requestor_phone, presence: {message: 'Phone number must not be blank'}
  validates :requestor_project, presence: {message: 'Project must not be blank'}
  validates :requestor_work_directive, presence: {message: 'Work directive must not be blank'}
  validates :title, presence: {message: 'Job title must not be blank'}
  validates :rwp, presence: {message: 'Please select yes or no regarding RWP certification'}
  validates :ocs, presence: {message: 'Please select yes or no regarding OCS'}
  validates :disturb, presence: {message: 'Please select yes or no regarding track disturbances'}
  validates :rrm, presence: {message: 'Please select yes or no regarding RRM'}
  validates :foul, presence: {message: 'Please select yes or no regarding fouling track'}
  validates :crossings, presence: {message: 'Please select yes or no regarding disabled crossings'}
  validates :underground, presence: {message: 'Please select yes or no regarding underground work'}
  validates :flagging, presence: {message: 'Please select yes or no regarding traffic control'}

  validate :mon_fields
  validate :tue_fields
  validate :wed_fields
  validate :thu_fields
  validate :fri_fields
  validate :sat_fields
  validate :sun_fields

  scope :filter_by_show_cancelled, -> (hide) {  where cancelled: 0 }
  scope :filter_by_show_pending, -> (hide) {  joins(:weekly).where("pending = ?", false) }
  scope :filter_by_show_approved, -> (hide) {  joins(:weekly).where("approved = ?", false) }
  scope :filter_by_show_rejected, -> (hide) {  joins(:weekly).where("rejected = ?", false) }

  scope :filter_by_night_work, -> (night_work) { where night_work: night_work }
  scope :filter_by_day_work, -> (day_work) { where night_work: 0 }
  scope :filter_by_week, -> (week) { where week: week }
  scope :filter_by_filter_week, -> (week) { where week: week }
  scope :filter_by_year, -> (year) { where year: year }
  scope :filter_by_filter_year, -> (year) { where year: year }
  scope :filter_by_single_tracking, -> (single_tracking) { joins(:weekly).where("single_tracking = ?", single_tracking)}
  scope :filter_by_no_single_tracking, -> (no_single_tracking) { joins(:weekly).where("single_tracking = ?", false)}
  scope :filter_by_mt1, -> (mt1) { joins(:weekly).where("mt1 = ?", mt1)}
  scope :filter_by_mt2, -> (mt2) { joins(:weekly).where("mt2 = ?", mt2)}
  scope :filter_by_mt3, -> (mt3) { joins(:weekly).where("mt3 = ?", mt3)}
  scope :filter_by_mt4, -> (mt4) { joins(:weekly).where("mt4 = ?", mt4)}
  scope :filter_by_other, -> (other) { joins(:weekly).where("other = ?", other)}
  scope :filter_by_taw, -> (taw) { joins(:weekly).where("taw = ?", taw)}
  scope :filter_by_form_b, -> (form_b) { joins(:weekly).where("form_b = ?", form_b)}
  scope :filter_by_form_c, -> (form_c) { joins(:weekly).where("form_c = ?", form_c)}
  scope :filter_by_track_and_time, -> (track_and_time) { joins(:weekly).where("track_and_time = ?", track_and_time)}
  scope :filter_by_contractor, -> (contractor) { joins(:weekly).where("contractor like ?", "#{contractor}%")}
  scope :filter_by_rwp, -> (rwp) { joins(:weekly).where("rwp = ?", rwp)}
  scope :filter_by_ocs, -> (ocs) { joins(:weekly).where("ocs = ?", ocs)}
  scope :filter_by_disturb, -> (disturb) { joins(:weekly).where("disturb = ?", disturb)}
  scope :filter_by_rrm, -> (rrm) { joins(:weekly).where("rrm = ?", rrm)}
  scope :filter_by_foul, -> (foul) { joins(:weekly).where("foul = ?", foul)}
  scope :filter_by_crossings, -> (crossings) { joins(:weekly).where("crossings = ?", crossings)}
  scope :filter_by_underground, -> (underground) { joins(:weekly).where("underground = ?", underground)}
  scope :filter_by_flagging, -> (flagging) { joins(:weekly).where("flagging = ?", flagging)}


  CP_ARRAY = [['N.L. CP 4th', 1],
        ['S.L. CP 4th', 2],
        ['N.L. CP Common', 3],
        ['S.L. CP Common', 4],
        ['N.L. CP Army', 5],
        ['S.L. CP Army', 6],
        ['N.L. CP Tunnel', 7],
        ['S.L. CP Tunnel', 8],
        ['N.L. CP Geneva', 9],
        ['S.L. CP Geneva', 10],
        ['N.L. CP Brisbane', 11],
        ['S.L. CP Brisbane', 12],
        ['N.L. CP Sierra', 13],
        ['S.L. CP Sierra', 14],
        ['N.L. CP Scott', 15],
        ['S.L. CP Scott', 16],
        ['N.L. CP Center', 17],
        ['S.L. CP Center', 18],
        ['N.L. CP Bart', 19],
        ['S.L. CP Bart', 20],
        ['N.L. CP Trousdale', 21],
        ['S.L. CP Trousdale', 22],
        ['N.L. CP Palm', 23],
        ['S.L. CP Palm', 24],
        ['N.L. CP Ralston', 25],
        ['S.L. CP Ralston', 26],
        ['N.L. CP Dumbarton', 27],
        ['S.L. CP Dumbarton', 28],
        ['N.L. CP Junction', 29],
        ['S.L. CP Junction', 30],
        ['N.L. CP Alma', 31],
        ['S.L. CP Alma', 32],
        ['N.L. CP Mayfield', 33],
        ['S.L. CP Mayfield', 34],
        ['N.L. CP Mary', 35],
        ['S.L. CP Mary', 36],
        ['N.L. CP Hendy', 37],
        ['S.L. CP Hendy', 38],
        ['N.L. CP Bowers', 39],
        ['S.L. CP Bowers', 40],
        ['N.L. CP De La Cruz', 41],
        ['S.L. CP De La Cruz', 42],
        ['N.L. CP Coast', 43],
        ['S.L. CP Coast', 44],
        ['N.L. CP Franklin', 45],
        ['S.L. CP Franklin', 46],
        ['N.L. CP Stockton', 47],
        ['S.L. CP Stockton', 48],
        ['N.L. CP Shark', 49],
        ['S.L. CP Shark', 50],
        ['N.L. CP Alameda', 51],
        ['S.L. CP Alameda', 52],
        ['N.L. CP Bird', 53],
        ['S.L. CP Bird', 54],
        ['N.L. CP Delmas', 55],
        ['S.L. CP Delmas', 56],
        ['N.L. CP Mack', 57],
        ['S.L. CP Mack', 58],
        ['N.L. CP Michael', 59],
        ['S.L. CP Michael', 60],
        ['N.L. CP Lick', 61],
        ['S.L. CP Lick', 62]]

  def mon_fields
    if mon ==1
      [["worker_primary", "Primary worker"], ["start_time", "Start time"], ["end_time", "End time"], ["b_time", "Briefing start time"], ["b_location", "Briefing location"], ["onsite_name", "Onsite contact name"], ["onsite_number", "Onsite contact number"], ["single_track", "Single tracking"]].each do |field|
        if monday_hash[field[0]] == "" || monday_hash[field[0]] == nil || monday_hash[field[0]] == "-"
          errors.add(:mon, "#{field[1]} must be populated for Monday")
        end
      end
    end
  end

  def tue_fields
    if tue ==1
      [["worker_primary", "Primary worker"], ["start_time", "Start time"], ["end_time", "End time"], ["b_time", "Briefing start time"], ["b_location", "Briefing location"], ["onsite_name", "Onsite contact name"], ["onsite_number", "Onsite contact number"], ["single_track", "Single tracking"]].each do |field|
        if tuesday_hash[field[0]] == "" || tuesday_hash[field[0]] == nil || tuesday_hash[field[0]] == "-"
          errors.add(:tue, "#{field[1]} must be populated for Tuesday")
        end
      end
    end
  end

  def wed_fields
    if wed ==1
      [["worker_primary", "Primary worker"], ["start_time", "Start time"], ["end_time", "End time"], ["b_time", "Briefing start time"], ["b_location", "Briefing location"], ["onsite_name", "Onsite contact name"], ["onsite_number", "Onsite contact number"], ["single_track", "Single tracking"]].each do |field|
        if wednesday_hash[field[0]] == "" || wednesday_hash[field[0]] == nil || wednesday_hash[field[0]] == "-"
          errors.add(:wed, "#{field[1]} must be populated for Wednesday")
        end
      end
    end
  end

  def thu_fields
    if thu ==1
      [["worker_primary", "Primary worker"], ["start_time", "Start time"], ["end_time", "End time"], ["b_time", "Briefing start time"], ["b_location", "Briefing location"], ["onsite_name", "Onsite contact name"], ["onsite_number", "Onsite contact number"], ["single_track", "Single tracking"]].each do |field|
        if thursday_hash[field[0]] == "" || thursday_hash[field[0]] == nil || thursday_hash[field[0]] == "-"
          errors.add(:thu, "#{field[1]} must be populated for Thursday")
        end
      end
    end
  end

  def fri_fields
    if fri ==1
      [["worker_primary", "Primary worker"], ["start_time", "Start time"], ["end_time", "End time"], ["b_time", "Briefing start time"], ["b_location", "Briefing location"], ["onsite_name", "Onsite contact name"], ["onsite_number", "Onsite contact number"], ["single_track", "Single tracking"]].each do |field|
        if friday_hash[field[0]] == "" || friday_hash[field[0]] == nil || friday_hash[field[0]] == "-"
          errors.add(:fri, "#{field[1]} must be populated for Friday")
        end
      end
    end
  end

  def sat_fields
    if sat ==1
      [["worker_primary", "Primary worker"], ["start_time", "Start time"], ["end_time", "End time"], ["b_time", "Briefing start time"], ["b_location", "Briefing location"], ["onsite_name", "Onsite contact name"], ["onsite_number", "Onsite contact number"], ["single_track", "Single tracking"]].each do |field|
        if saturday_hash[field[0]] == "" || saturday_hash[field[0]] == nil || saturday_hash[field[0]] == "-"
          errors.add(:sat, "#{field[1]} must be populated for Saturday")
        end
      end
    end
  end

  def sun_fields
    if sun ==1

app/controllers/api/v1/requests_controller.rb
class Api::V1::RequestsController < ApplicationController

  def update
    @request = Request.where(id: params[:id])[0]
    @user = current_user
    if params["rnotes"]
      case params["day"]
      when "mon"
        @request.requestor_notes_mon = params["rnotes"]
      when "tue"
        @request.requestor_notes_tue = params["rnotes"]
      when "wed"
        @request.requestor_notes_wed = params["rnotes"]
      when "thu"
        @request.requestor_notes_thu = params["rnotes"]
      when "fri"
        @request.requestor_notes_fri = params["rnotes"]
      when "sat"
        @request.requestor_notes_sat = params["rnotes"]
      when "sun"
        @request.requestor_notes_sun = params["rnotes"]
      end
    end
    if params["anotes"]
      case params["day"]
      when "mon"
        @request.admin_notes_mon = params["anotes"]
      when "tue"
        @request.admin_notes_tue = params["anotes"]
      when "wed"
        @request.admin_notes_wed = params["anotes"]
      when "thu"
        @request.admin_notes_thu = params["anotes"]
      when "fri"
        @request.admin_notes_fri = params["anotes"]
      when "sat"
        @request.admin_notes_sat = params["anotes"]
      when "sun"
        @request.admin_notes_sun = params["anotes"]
      end
    end
    if params["inotes"]
      case params["day"]
      when "mon"
        @request.inspector_notes_mon = params["inotes"]
      when "tue"
        @request.inspector_notes_tue = params["inotes"]
      when "wed"
        @request.inspector_notes_wed = params["inotes"]
      when "thu"
        @request.inspector_notes_thu = params["inotes"]
      when "fri"
        @request.inspector_notes_fri = params["inotes"]
      when "sat"
        @request.inspector_notes_sat = params["inotes"]
      when "sun"
        @request.inspector_notes_sun = params["inotes"]
      end
    end
    @request.save
  end

  def show
    @request = Request.where(id: params[:id])[0]
    if params["intention"] == "request body"
      if current_user.role == 'user'
        response = (@request.contractor == current_user.company)
      else
        response = true
      end
    elsif params["intention"] == "notes"
      if current_user.role == 'user' && params["type"] == "requestor"
        response = (@request.contractor == current_user.company)
      elsif current_user.role == 'admin' && (params["type"] == "admin" || params["type"] == "inspector")
        response = true
      elsif current_user.role == 'inspector' && params["type"] == "inspector"
        response = true
      elsif current_user.role == 'superadmin'
        response = true
      else
        response = false
      end
    end
    render json: response
  end

  def destroy
    @request = Request.where(id: params[:id])[0]
    @request.destroy
  end

end

app/views/requests/edit.html.erb

<%= form_for @request do |f| %>
<br>
<br>

<div class="form_nav">
  <div id="form_nav_container">
  <div>
    <%= link_to 'Discard Changes', edit_request_path(@request), data: { confirm: 'Unsaved changes will be lost. Proceed?' }, class: "form_nav_link" %>
  </div>
  <div>
<%= link_to 'Cancel Request', request_cancel_path(@request), method: :put, data: { confirm: 'This request will be cancelled. Proceed?' }, class: "form_nav_link" %>
</div>
</div>
</div>
<br>
<div class="form_action_header"><h2>Editing Request "<%= @request.title %>"</h2></div>
<br>
<%= render "layouts/request_form", f: f %>
<% end %>

app/views/requests/new.html.erb
<%= form_for @request do |f| %>
<br>
<br>
<input type="hidden" name="user_default_color" id="user_default_color" data-current="<%= @user.default_color %>" value="">
<div class="form_nav">
  <%= link_to 'Reset Form', new_request_path, class: "form_nav_link", data: {confirm: "All unsaved changes will be lost. Proceed?"} %>
</div>
<br>
<% if @copied_from != nil %>
<div class="form_action_header"><h2>Copying From Request "<%= @copied_from.title %>"</h2></div>
<div id="copied_request" class="hidden">true</div>
<%= hidden_field_tag("copied", value = true) %>
<% end %>
<br>

<%= render "layouts/request_form", f: f %>
<% end %>

app/views/requests/show.html.erb
<div class="<%= @request.color %>">
<h1 class="<%= @request.color %>"><%= @request.title %></h1>
<h3 class="<%= @request.color %>">  Week <%= @request.week %>, <%= @request.year %></h3>
</div>
<div class="margin_wrapper">
  <%= link_to 'Edit Request', edit_request_path(@request), class: "fakebutton" %>
  <%= link_to 'Copy Request', new_request_path(:copyfrom => @request.id), class: "fakebutton" %>
  <!-- <a href="#" class="fakebutton">Cancel Days</a> -->
  <br>

  <% @request.attachments.each do |attachment| %>
  <div class="level">
    <%= link_to attachment.filename, rails_blob_path(attachment, only_path: true) %>
  </div>
  <% end %>

  <h3 class="underline">Current Approval Status</h3>
  <div class = "inlineblock">
    <ul class="showstatus">
      <li><div class="day_header">Monday:</div>
        <div class="approval_summary">
          <div class="approvals_bar_container">
            <div class="approvals_bar_block <% if @request.mon == 1 %><%= @request.approval.group_1_mon %><% else %>not_scheduled<% end %>">1</div>
            <div class="approvals_bar_block <% if @request.mon == 1 %><%= @request.approval.group_2_mon %><% else %>not_scheduled<% end %>">2</div>
            <div class="approvals_bar_block <% if @request.mon == 1 %><%= @request.approval.group_3_mon %><% else %>not_scheduled<% end %>">3</div>
            <div class="approvals_bar_block <% if @request.mon == 1 %><%= @request.approval.group_4_mon %><% else %>not_scheduled<% end %>">4</div>
          </div>
          <% if @request.mon == 1 %>
            <div class="status_text <%= @request.daystatus(@request.approval.group_1_mon, @request.approval.group_2_mon, @request.approval.group_3_mon, @request.approval.group_4_mon) %>"><%= @request.daystatus(@request.approval.group_1_mon, @request.approval.group_2_mon, @request.approval.group_3_mon, @request.approval.group_4_mon).capitalize %></div>
          <% else %>
            <div class="status_text not_scheduled">No work Scheduled</div>
          <% end %>
        </div>
      </li>
      <li><div class="day_header">Tuesday:</div>
        <div class="approval_summary">
          <div class="approvals_bar_container">
            <div class="approvals_bar_block <% if @request.tue == 1 %><%= @request.approval.group_1_tue %><% else %>not_scheduled<% end %>">1</div>
            <div class="approvals_bar_block <% if @request.tue == 1 %><%= @request.approval.group_2_tue %><% else %>not_scheduled<% end %>">2</div>
            <div class="approvals_bar_block <% if @request.tue == 1 %><%= @request.approval.group_3_tue %><% else %>not_scheduled<% end %>">3</div>
            <div class="approvals_bar_block <% if @request.tue == 1 %><%= @request.approval.group_4_tue %><% else %>not_scheduled<% end %>">4</div>
          </div>
          <% if @request.tue == 1 %>
            <div class="status_text <%= @request.daystatus(@request.approval.group_1_tue, @request.approval.group_2_tue, @request.approval.group_3_tue, @request.approval.group_4_tue) %>"><%= @request.daystatus(@request.approval.group_1_tue, @request.approval.group_2_tue, @request.approval.group_3_tue, @request.approval.group_4_tue).capitalize %></div>
          <% else %>
            <div class="status_text not_scheduled">No work Scheduled</div>
          <% end %>
        </div>
      </li>
      <li><div class="day_header">Wednesday:</div>
        <div class="approval_summary">
          <div class="approvals_bar_container">
            <div class="approvals_bar_block <% if @request.wed == 1 %><%= @request.approval.group_1_wed %><% else %>not_scheduled<% end %>">1</div>
            <div class="approvals_bar_block <% if @request.wed == 1 %><%= @request.approval.group_2_wed %><% else %>not_scheduled<% end %>">2</div>
            <div class="approvals_bar_block <% if @request.wed == 1 %><%= @request.approval.group_3_wed %><% else %>not_scheduled<% end %>">3</div>
            <div class="approvals_bar_block <% if @request.wed == 1 %><%= @request.approval.group_4_wed %><% else %>not_scheduled<% end %>">4</div>
          </div>
          <% if @request.wed == 1 %>
            <div class="status_text <%= @request.daystatus(@request.approval.group_1_wed, @request.approval.group_2_wed, @request.approval.group_3_wed, @request.approval.group_4_wed) %>"><%= @request.daystatus(@request.approval.group_1_wed, @request.approval.group_2_wed, @request.approval.group_3_wed, @request.approval.group_4_wed).capitalize %></div>
          <% else %>
            <div class="status_text not_scheduled">No work Scheduled</div>
          <% end %>
        </div>
      </li>
      <li><div class="day_header">Thursday:</div>
        <div class="approval_summary">
          <div class="approvals_bar_container">
            <div class="approvals_bar_block <% if @request.thu == 1 %><%= @request.approval.group_1_thu %><% else %>not_scheduled<% end %>">1</div>
            <div class="approvals_bar_block <% if @request.thu == 1 %><%= @request.approval.group_2_thu %><% else %>not_scheduled<% end %>">2</div>
            <div class="approvals_bar_block <% if @request.thu == 1 %><%= @request.approval.group_3_thu %><% else %>not_scheduled<% end %>">3</div>
            <div class="approvals_bar_block <% if @request.thu == 1 %><%= @request.approval.group_4_thu %><% else %>not_scheduled<% end %>">4</div>
          </div>
          <% if @request.thu == 1 %>
            <div class="status_text <%= @request.daystatus(@request.approval.group_1_thu, @request.approval.group_2_thu, @request.approval.group_3_thu, @request.approval.group_4_thu) %>"><%= @request.daystatus(@request.approval.group_1_thu, @request.approval.group_2_thu, @request.approval.group_3_thu, @request.approval.group_4_thu).capitalize %></div>
          <% else %>
            <div class="status_text not_scheduled">No work Scheduled</div>
          <% end %>
        </div>
      </li>
      <li><div class="day_header">Friday:</div>
        <div class="approval_summary">
          <div class="approvals_bar_container">
            <div class="approvals_bar_block <% if @request.fri == 1 %><%= @request.approval.group_1_fri %><% else %>not_scheduled<% end %>">1</div>
            <div class="approvals_bar_block <% if @request.fri == 1 %><%= @request.approval.group_2_fri %><% else %>not_scheduled<% end %>">2</div>
            <div class="approvals_bar_block <% if @request.fri == 1 %><%= @request.approval.group_3_fri %><% else %>not_scheduled<% end %>">3</div>
            <div class="approvals_bar_block <% if @request.fri == 1 %><%= @request.approval.group_4_fri %><% else %>not_scheduled<% end %>">4</div>
          </div>
          <% if @request.fri == 1 %>
            <div class="status_text <%= @request.daystatus(@request.approval.group_1_fri, @request.approval.group_2_fri, @request.approval.group_3_fri, @request.approval.group_4_fri) %>"><%= @request.daystatus(@request.approval.group_1_fri, @request.approval.group_2_fri, @request.approval.group_3_fri, @request.approval.group_4_fri).capitalize %></div>
          <% else %>
            <div class="status_text not_scheduled">No work Scheduled</div>
          <% end %>
        </div>
      </li>
      <li><div class="day_header">Saturday:</div>
        <div class="approval_summary">
          <div class="approvals_bar_container">
            <div class="approvals_bar_block <% if @request.sat == 1 %><%= @request.approval.group_1_sat %><% else %>not_scheduled<% end %>">1</div>
            <div class="approvals_bar_block <% if @request.sat == 1 %><%= @request.approval.group_2_sat %><% else %>not_scheduled<% end %>">2</div>
            <div class="approvals_bar_block <% if @request.sat == 1 %><%= @request.approval.group_3_sat %><% else %>not_scheduled<% end %>">3</div>
            <div class="approvals_bar_block <% if @request.sat == 1 %><%= @request.approval.group_4_sat %><% else %>not_scheduled<% end %>">4</div>
          </div>
          <% if @request.sat == 1 %>
            <div class="status_text <%= @request.daystatus(@request.approval.group_1_sat, @request.approval.group_2_sat, @request.approval.group_3_sat, @request.approval.group_4_sat) %>"><%= @request.daystatus(@request.approval.group_1_sat, @request.approval.group_2_sat, @request.approval.group_3_sat, @request.approval.group_4_sat).capitalize %></div>
          <% else %>
            <div class="status_text not_scheduled">No work Scheduled</div>
          <% end %>
        </div>
      </li>
      <li><div class="day_header">Sunday:</div>
        <div class="approval_summary">
          <div class="approvals_bar_container">
            <div class="approvals_bar_block <% if @request.sun == 1 %><%= @request.approval.group_1_sun %><% else %>not_scheduled<% end %>">1</div>
            <div class="approvals_bar_block <% if @request.sun == 1 %><%= @request.approval.group_2_sun %><% else %>not_scheduled<% end %>">2</div>
            <div class="approvals_bar_block <% if @request.sun == 1 %><%= @request.approval.group_3_sun %><% else %>not_scheduled<% end %>">3</div>
            <div class="approvals_bar_block <% if @request.sun == 1 %><%= @request.approval.group_4_sun %><% else %>not_scheduled<% end %>">4</div>
          </div>
          <% if @request.sun == 1 %>
            <div class="status_text <%= @request.daystatus(@request.approval.group_1_sun, @request.approval.group_2_sun, @request.approval.group_3_sun, @request.approval.group_4_sun) %>"><%= @request.daystatus(@request.approval.group_1_sun, @request.approval.group_2_sun, @request.approval.group_3_sun, @request.approval.group_4_sun).capitalize %></div>
          <% else %>
            <div class="status_text not_scheduled">No work Scheduled</div>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
  <% if @user.role == "superadmin" %>
    <div class="superadmin_buttons">
      <div>
        <button type="button" class="superadmin_approve" data-req="<%= @request.id %>" data-day="0" data-mon="true">Approve all groups</button>
      </div>
      <div>
        <button type="button" class="superadmin_approve" data-req="<%= @request.id %>" data-day="1" data-tue="true">Approve all groups</button>
      </div>
      <div>
        <button type="button" class="superadmin_approve" data-req="<%= @request.id %>" data-day="2" data-wed="true">Approve all groups</button>
      </div>
      <div>
        <button type="button" class="superadmin_approve" data-req="<%= @request.id %>" data-day="3" data-thu="true">Approve all groups</button>
      </div>
      <div>
        <button type="button" class="superadmin_approve" data-req="<%= @request.id %>" data-day="4" data-fri="true">Approve all groups</button>
      </div>
      <div>
        <button type="button" class="superadmin_approve" data-req="<%= @request.id %>" data-day="5" data-sat="true">Approve all groups</button>
      </div>
      <div>
        <button type="button" class="superadmin_approve" data-req="<%= @request.id %>" data-day="6" data-sun="true">Approve all groups</button>
      </div>
    </div>
  <% end %>
    <br>
    <div id="approve_all_for_group">
      Approve all days for group:
      <div>
      <% if @user.approval_group == 1 || @user.role == "superadmin" %>
      <button type="button" class="group_approve" data-req="<%= @request.id %>" data-group="1">1</button>
      <% end %>
      <% if @user.approval_group == 2 || @user.role == "superadmin" %>
      <button type="button" class="group_approve" data-req="<%= @request.id %>" data-group="2">2</button>
      <% end %>
      <% if @user.approval_group == 3 || @user.role == "superadmin" %>
      <button type="button" class="group_approve" data-req="<%= @request.id %>" data-group="3">3</button>
      <% end %>
      <% if @user.approval_group == 4 || @user.role == "superadmin" %>
      <button type="button" class="group_approve" data-req="<%= @request.id %>" data-group="4">4</button>
      <% end %>
      </div>
    </div>
    <br>

    <!-- <h1>Notes</h1> -->

    <!-- <h1>Change Log</h1> -->
</div>