config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  get 'landing/index'
  root 'landing#index'

  resources :requests
  resources :profiles
  resources :changelogs
  resources :contractors
  resources :registrations
  resources :signuptokens

  resources :requests do
    resources :changelogs
    patch :approve
    put :approve
    patch :cancel
    put :cancel
  end

  resources :requests do
    get 'note', on: :new
  end

  namespace :api do
    namespace :v1 do
      resources :requests, only: [:index, :update, :show, :create, :destroy]
    end
  end
  namespace :api do
    namespace :v1 do
      resources :approvals, only: [:index, :update, :show, :create]
    end
  end
  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index, :update, :show, :create]
    end
  end
  namespace :api do
    namespace :v1 do
      resources :newsfeeds, only: [:index, :update, :show, :create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :signuptokens, only: [:index, :update, :show, :create, :destroy]
    end
  end


  root to: 'landing#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Right to Work Request Portal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="top_nav_bar">
      <% if user_signed_in? %>
      <a class='nav_link' href='<%= root_path %>'>Line Sheet</a>
      <a class='nav_link' href='<%= new_request_path %>'>New Request</a>
      <% end %>
      <div id="account_overlay" class="hide">
        <% if user_signed_in? %>
          <% if @user.role == "admin" || @user.role == "superadmin" %>
          <a class='nav_link' href='<%= profiles_path %>'>Users</a>
          <% end %>
          <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete,  :class => "nav_link" %>
          <a class='nav_link' href='<%= edit_user_registration_path(current_user.id) %>'>My Account</a>

        <% else %>
          <%= link_to 'Sign In', new_user_session_path, :class => "nav_link"  %>
          <%= link_to 'Sign Up', registrations_path, :class => "nav_link"  %>
        <% end %>
      </div>
    </div>
    <div id="alert_box">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>